name: 'CODICENSE License Scan (Minimal Wrapper)'
description: 'Runs codicense CLI in CI. Prefer calling the CLI directly.'
author: 'CODICENSE Team'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  fail-on:
    description: 'Fail on these severity levels (critical,high,medium,low, or none)'
    required: false
    default: 'critical,high'
  path:
    description: 'Path to scan (relative to repo root)'
    required: false
    default: '.'

outputs:
  result:
    description: 'Scan result JSON'
  exit-code:
    description: 'Exit code (0 = success, 1 = issues found)'

runs:
  using: 'composite'
  steps:
    - name: Run codicense
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        npx --yes codicense@1.0.0 ci --fail-on "${{ inputs.fail-on }}"

