/**
 * PR Generator - Creates draft pull requests for fixes
 * 
 * Generates GitHub PR content with deterministic branch names and commits.
 */

import type { FixSuggestion } from '../ili/types';
import type { Patch } from './patch-generator';

export interface PRContent {
  branchName: string;
  commitMessage: string;
  prTitle: string;
  prBody: string;
  labels: string[];
}

export class PRGenerator {
  /**
   * Generate PR content for a fix
   */
  static generatePR(
    fix: FixSuggestion,
    patch: Patch,
    conflictId: string
  ): PRContent {
    const timestamp = this.isDeterministic() 
      ? '0000000000' 
      : Date.now().toString().slice(-10);

    const branchName = this.generateBranchName(fix.strategy, conflictId, timestamp);
    const commitMessage = this.generateCommitMessage(fix, patch);
    const prTitle = this.generatePRTitle(fix);
    const prBody = this.generatePRBody(fix, patch);
    const labels = this.generateLabels(fix);

    return {
      branchName,
      commitMessage,
      prTitle,
      prBody,
      labels,
    };
  }

  /**
   * Generate deterministic branch name
   */
  private static generateBranchName(
    strategy: string,
    conflictId: string,
    timestamp: string
  ): string {
    const safeConflictId = conflictId.replace(/[^a-z0-9]/gi, '-').toLowerCase();
    return `codicense/${strategy}-${safeConflictId}-${timestamp}`;
  }

  /**
   * Generate commit message
   */
  private static generateCommitMessage(fix: FixSuggestion, patch: Patch): string {
    const lines: string[] = [];
    
    lines.push(`fix(licenses): ${patch.description}`);
    lines.push('');
    lines.push(`This commit ${fix.description.toLowerCase()}.`);
    lines.push('');
    lines.push(`Strategy: ${fix.strategy}`);
    lines.push(`Effort: ${fix.effort}`);
    lines.push('');
    lines.push('Generated by Codicense');
    
    return lines.join('\n');
  }

  /**
   * Generate PR title
   */
  private static generatePRTitle(fix: FixSuggestion): string {
    return `[License Fix] ${fix.description}`;
  }

  /**
   * Generate PR body
   */
  private static generatePRBody(fix: FixSuggestion, patch: Patch): string {
    const lines: string[] = [];

    lines.push('## License Compatibility Fix');
    lines.push('');
    lines.push(`This PR resolves a license compatibility issue by: **${fix.description}**`);
    lines.push('');
    lines.push('### Fix Details');
    lines.push('');
    lines.push(`- **Strategy**: ${fix.strategy}`);
    lines.push(`- **Effort**: ${fix.effort}`);
    if (fix.estimatedTime) {
      lines.push(`- **Estimated Time**: ${fix.estimatedTime}`);
    }
    lines.push('');
    lines.push('### Changes');
    lines.push('');
    lines.push('```diff');
    lines.push(patch.diff);
    lines.push('```');
    lines.push('');
    lines.push('### Implementation Notes');
    lines.push('');
    lines.push(fix.implementation);
    lines.push('');
    
    if (fix.tradeoffs.length > 0) {
      lines.push('### Tradeoffs');
      lines.push('');
      for (const tradeoff of fix.tradeoffs) {
        lines.push(`- ${tradeoff}`);
      }
      lines.push('');
    }

    lines.push('### Testing Checklist');
    lines.push('');
    lines.push('- [ ] All existing tests pass');
    lines.push('- [ ] No new license conflicts introduced');
    lines.push('- [ ] Functionality unchanged');
    lines.push('- [ ] Dependencies updated in lockfile');
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('*Generated by [Codicense](https://github.com/codicense/codicense)*');

    return lines.join('\n');
  }

  /**
   * Generate PR labels
   */
  private static generateLabels(fix: FixSuggestion): string[] {
    const labels = ['license-fix', 'automated'];

    if (fix.effort === 'low') {
      labels.push('easy-fix');
    } else if (fix.effort === 'high') {
      labels.push('complex-fix');
    }

    if (fix.strategy === 'replace') {
      labels.push('dependency-update');
    } else if (fix.strategy === 'remove') {
      labels.push('breaking-change');
    }

    return labels;
  }

  /**
   * Check if deterministic mode is enabled
   */
  private static isDeterministic(): boolean {
    return process.env.CODICENSE_DETERMINISTIC === '1';
  }

  /**
   * Generate CLI commands for creating the PR
   */
  static generateCLICommands(pr: PRContent, patch: Patch): string {
    const lines: string[] = [];

    lines.push('# Create fix branch and commit');
    lines.push(`git checkout -b ${pr.branchName}`);
    lines.push('');
    lines.push('# Apply changes');
    for (const op of patch.operations) {
      if (op.file === 'package.json') {
        lines.push(`# Update ${op.file} manually or:`);
        if (op.before && op.after) {
          lines.push(`sed -i 's/${op.before}/${op.after}/g' ${op.file}`);
        }
      }
    }
    lines.push('');
    lines.push('# Commit changes');
    lines.push(`git add -A`);
    lines.push(`git commit -m "${pr.commitMessage.split('\n')[0]}"`);
    lines.push('');
    lines.push('# Push and create PR');
    lines.push(`git push origin ${pr.branchName}`);
    lines.push(`gh pr create --title "${pr.prTitle}" --body "See commit description"`);

    return lines.join('\n');
  }
}

